name: Deploy Novel Search API

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Deploy to server
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVER_USER }}
        password: ${{ secrets.SERVER_PASSWORD }}
        port: 22
        timeout: 30s
        command_timeout: 10m
        script_stop: true
        script: |
          # 安装系统依赖
          sudo apt-get update
          sudo apt-get install -y python3-venv python3-pip git
          
          # 进入项目目录
          cd /var/www/novel-api
          
          # 设置SSH环境变量
          export HOME=/root
          export SSH_AUTH_SOCK=""

          # 检查可用的SSH密钥
          SSH_KEY=""
          if [ -f /root/.ssh/id_ed25519 ]; then
            SSH_KEY="/root/.ssh/id_ed25519"
            echo "找到 Ed25519 密钥: $SSH_KEY"
          elif [ -f /root/.ssh/id_rsa ]; then
            SSH_KEY="/root/.ssh/id_rsa"
            echo "找到 RSA 密钥: $SSH_KEY"
          elif [ -f ~/.ssh/id_ed25519 ]; then
            SSH_KEY="~/.ssh/id_ed25519"
            echo "找到用户 Ed25519 密钥: $SSH_KEY"
          elif [ -f ~/.ssh/id_rsa ]; then
            SSH_KEY="~/.ssh/id_rsa"
            echo "找到用户 RSA 密钥: $SSH_KEY"
          else
            echo "❌ 未找到SSH密钥文件"
          fi
          
          # 启动SSH Agent并添加密钥
          if [ -n "$SSH_KEY" ]; then
            echo "配置SSH Agent..."
            eval "$(ssh-agent -s)"
            
            # 确保密钥权限正确
            chmod 600 "$SSH_KEY" 2>/dev/null || echo "无法修改密钥权限"
            
            # 添加密钥到SSH Agent
            ssh-add "$SSH_KEY" 2>/dev/null && echo "✅ SSH密钥已加载" || echo "⚠️ SSH密钥加载失败"
          fi
          
          # 拉取最新代码（使用SSH）
          git pull origin main
          
          # 创建虚拟环境（如果不存在）
          python3 -m venv venv
          
          # 激活虚拟环境并安装依赖
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt
          
          # 创建必要的目录
          mkdir -p downloads
          mkdir -p logs
          
          # 停止现有服务
          sudo systemctl stop novel-api || true
          
          # 创建systemd服务文件
          sudo tee /etc/systemd/system/novel-api.service > /dev/null <<EOF
          [Unit]
          Description=Novel Search API
          After=network.target
          
          [Service]
          Type=simple
          User=www-data
          Group=www-data
          WorkingDirectory=/var/www/novel-api
          Environment=PATH=/var/www/novel-api/venv/bin
          ExecStart=/var/www/novel-api/venv/bin/python -m uvicorn app.main:app --host 0.0.0.0 --port 8000
          Restart=always
          RestartSec=10
          
          [Install]
          WantedBy=multi-user.target
          EOF
          
          # 重新加载systemd配置
          sudo systemctl daemon-reload
          
          # 启动服务
          sudo systemctl start novel-api
          sudo systemctl enable novel-api
          
          # 检查服务状态
          sudo systemctl status novel-api
          
    - name: Setup Nginx
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVER_USER }}
        password: ${{ secrets.SERVER_PASSWORD }}
        port: 22
        timeout: 30s
        command_timeout: 10m
        script: |
          # 创建Nginx配置文件
          sudo tee /etc/nginx/sites-available/novel-api > /dev/null <<EOF
          server {
              listen 80;
              server_name slwen.cn;  # 替换为您的域名
              
              location / {
                  proxy_pass http://127.0.0.1:8000;
                  proxy_set_header Host \$host;
                  proxy_set_header X-Real-IP \$remote_addr;
                  proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
                  proxy_set_header X-Forwarded-Proto \$scheme;
                  
                  # 支持大文件下载
                  proxy_max_temp_file_size 0;
                  proxy_buffering off;
                  proxy_request_buffering off;
              }
              
              # 静态文件缓存
              location ~* \.(txt|epub|pdf)$ {
                  expires 1d;
                  add_header Cache-Control "public, immutable";
              }
          }
          EOF
          
          # 启用站点
          sudo ln -sf /etc/nginx/sites-available/novel-api /etc/nginx/sites-enabled/
          
          # 测试Nginx配置
          sudo nginx -t
          
          # 重启Nginx
          sudo systemctl reload nginx
          
    - name: Health check
      run: |
        # 等待服务启动
        sleep 30
        
        # 健康检查
        curl -f http://${{ secrets.SERVER_IP }}:8000/ || exit 1
        echo "API服务启动成功！" 