name: Deploy Novel Search API

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Deploy to server
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVER_USER }}
        password: ${{ secrets.SERVER_PASSWORD }}
        port: 22
        timeout: 30s
        command_timeout: 10m
        script_stop: true
        script: |
          # 安装系统依赖
          sudo apt-get update
          sudo apt-get install -y python3-venv python3-pip git
          
          # 检查并创建项目目录
          if [ ! -d "/var/www/novel-api" ]; then
            echo "创建项目目录..."
            sudo mkdir -p /var/www/novel-api
            sudo chown $USER:$USER /var/www/novel-api
          fi
          
          # 进入项目目录
          cd /var/www/novel-api
          echo "当前目录: $(pwd)"

          # 停止现有服务
          sudo systemctl stop novel-api || true
          
          # 检查是否是Git仓库
          if [ ! -d ".git" ]; then
            echo "初始化Git仓库..."
            git init
            git remote add origin git@github.com:${{ github.repository }}.git
          fi
          
          # 设置SSH环境变量
          export HOME=/root
          export SSH_AUTH_SOCK=""

          # 检查可用的SSH密钥
          SSH_KEY=""
          if [ -f /root/.ssh/id_ed25519 ]; then
            SSH_KEY="/root/.ssh/id_ed25519"
            echo "找到 Ed25519 密钥: $SSH_KEY"
          elif [ -f /root/.ssh/id_rsa ]; then
            SSH_KEY="/root/.ssh/id_rsa"
            echo "找到 RSA 密钥: $SSH_KEY"
          elif [ -f ~/.ssh/id_ed25519 ]; then
            SSH_KEY="~/.ssh/id_ed25519"
            echo "找到用户 Ed25519 密钥: $SSH_KEY"
          elif [ -f ~/.ssh/id_rsa ]; then
            SSH_KEY="~/.ssh/id_rsa"
            echo "找到用户 RSA 密钥: $SSH_KEY"
          else
            echo "❌ 未找到SSH密钥文件"
          fi
          
          # 启动SSH Agent并添加密钥
          if [ -n "$SSH_KEY" ]; then
            echo "配置SSH Agent..."
            eval "$(ssh-agent -s)"
            
            # 确保密钥权限正确
            chmod 600 "$SSH_KEY" 2>/dev/null || echo "无法修改密钥权限"
            
            # 添加密钥到SSH Agent
            ssh-add "$SSH_KEY" 2>/dev/null && echo "✅ SSH密钥已加载" || echo "⚠️ SSH密钥加载失败"
          fi
          
          # 拉取最新代码（使用SSH）
          git pull origin main || echo "Git pull failed, but continuing..."
          
          echo "升级pip..."
          pip install --upgrade pip
          
          echo "安装Python依赖..."
          pip install -r requirements.txt
          
          # 创建必要的目录
          echo "创建必要目录..."
          mkdir -p downloads
          mkdir -p logs
          
          # 检查文件是否存在
          echo "检查关键文件..."
          ls -la requirements.txt || echo "requirements.txt不存在"
          ls -la app/main.py || echo "app/main.py不存在"
          
          # 重新加载systemd配置
          echo "重新加载systemd配置..."
          sudo systemctl daemon-reload
          
          # 启动服务
          echo "启动systemd服务..."
          sudo systemctl start novel-api
          sudo systemctl enable novel-api
          
          # 检查服务状态
          echo "=== 检查服务状态 ==="
          sudo systemctl status novel-api --no-pager
          
          # 检查端口是否监听
          echo "=== 检查端口监听 ==="
          netstat -tlnp | grep 8000 || echo "端口8000未监听"
          
          # 检查进程
          echo "=== 检查进程 ==="
          ps aux | grep uvicorn || echo "未找到uvicorn进程"
          
          # 检查日志
          echo "=== 检查服务日志 ==="
          sudo journalctl -u novel-api --no-pager -n 20
          
    - name: Health check
      run: |
        echo "=== 开始健康检查 ==="
        
        # 等待服务启动
        echo "等待服务启动..."
        sleep 30
        
        # 检查服务状态
        echo "检查服务状态..."
        ssh -o ConnectTimeout=10 ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} "sudo systemctl status novel-api --no-pager"
        
        # 检查端口
        echo "检查端口监听..."
        ssh -o ConnectTimeout=10 ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} "netstat -tlnp | grep 8000 || echo '端口8000未监听'"
        
        # 尝试健康检查
        echo "执行健康检查..."
        for i in {1..5}; do
          echo "尝试第 $i 次连接..."
          if curl -f --connect-timeout 10 http://${{ secrets.SERVER_IP }}:8000/; then
            echo "✅ API服务启动成功！"
            exit 0
          else
            echo "❌ 第 $i 次连接失败"
            sleep 10
          fi
        done
        
        echo "❌ 健康检查失败，服务可能未正常启动"
        exit 1 